### ISSUE TITLE
Bug: element visibility not working

### ISSUE THREAD

**Issue by dloewen** [Theme-Fusion/Fusion-Builder-Sample-Add-On#13]
After the Avada 5.1 update, element visibility is not working anymore.

The visibility CSS output in the header contains the wrong values, like this:

```CSS
@media screen and (max-width: 0px){.fusion-no-small-visibility{display:none !important;}}
@media screen and (min-width: 1px) and (max-width: 0px){.fusion-no-medium-visibility{display:none !important;}}
@media screen and (min-width: 1px){.fusion-no-large-visibility{display:none !important;}}
```
